import test from 'node:test';
import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import {once} from 'node:events';
import net from 'node:net';
import {fixture} from './fixtures.mjs';
import {createToken} from '../apps/api/src/auth.js';
import {saveOperation} from '../apps/api/src/operations.js';
const secret='wirehouse-test-secret';

test('API regression: scoped finance, persisted notification reads, validation and blocked sessions',async t=>{
  const f=fixture();t.after(f.cleanup);
  const period=new Date().toISOString().slice(0,7);
  const invoice=f.db.createBillingInvoice({leaseId:f.lease.id,period,rentAmount:1000,variableAmount:0,dueDate:`${period}-01`});
  f.db.createBillingPayment({invoiceId:invoice.id,amount:250,paidAt:`${period}-02`,method:'bank_transfer',reference:'test'});
  f.db.createBillingInvoice({leaseId:f.otherLease.id,period,rentAmount:9000,variableAmount:0,dueDate:`${period}-01`});
  saveOperation(f.db,f.admin,'expenses',null,{name:'Ремонт',propertyId:f.property.id,date:`${period}-03`,amount:100});
  const task=f.db.createTicket({unitId:f.unit.id,createdBy:f.admin.id,tenantId:f.tenant.id,assignedTo:f.worker.id,category:'electrical',priority:'urgent',title:'Проверить щит',description:'Проверка'});
  const socket=net.createServer();socket.listen(0,'127.0.0.1');await once(socket,'listening');const port=socket.address().port;await new Promise(r=>socket.close(r));
  const env={...process.env,API_HOST:'127.0.0.1',API_PORT:String(port),WAREHOUSE_DB_PATH:f.dbPath,ENABLE_DEMO_SEED:'false',DATABASE_URL:'',POSTGRES_URL:'',REDIS_URL:'',JWT_ACCESS_SECRET:secret,NOTIFICATION_CHANNELS:'in_app',TELEGRAM_BOT_TOKEN:'',VK_GROUP_TOKEN:''};
  let child;let output='';
  const start=async()=>{child=spawn(process.execPath,['apps/api/src/index.js'],{env,stdio:['ignore','pipe','pipe']});child.stdout.on('data',d=>output+=d);child.stderr.on('data',d=>output+=d);for(let i=0;i<100;i++){try{const r=await fetch(`http://127.0.0.1:${port}/health`);if(r.ok)return;}catch{}if(child.exitCode!==null)throw Error(output);await new Promise(r=>setTimeout(r,30));}throw Error(output);};
  const stop=async()=>{if(child && child.exitCode===null){child.kill('SIGTERM');await once(child,'exit');}};t.after(stop);
  const call=async(path,user=f.manager,method='GET',body)=>{const r=await fetch(`http://127.0.0.1:${port}${path}`,{method,headers:{'Content-Type':'application/json',Authorization:`Bearer ${createToken({sub:user.id,role:user.role},secret)}`},body:body?JSON.stringify(body):undefined});return {status:r.status,body:await r.json()};};
  await start();
  let overview=(await call('/api/dashboard/overview')).body;
  assert.equal(overview.finance.collectionBilled,1000);assert.equal(overview.finance.collectionPaid,250);assert.equal(overview.finance.collectionRate,25);assert.equal(overview.finance.noi,150);
  const tenant=(await call(`/api/tenants/${f.tenant.id}/detail`)).body;
  assert.equal(tenant.summary.paymentDiscipline,25);
  assert.equal(tenant.summary.arrearsAmount,750);
  assert.equal(tenant.payments.length,1);
  const notification=overview.notifications.find(n=>n.entityId===task.id);assert.ok(notification?.unread);
  assert.equal((await call(`/api/notifications/${notification.id}/read`,f.manager,'POST')).status,200);
  await stop();await start();
  overview=(await call('/api/dashboard/overview')).body;assert.equal(overview.notifications.find(n=>n.id===notification.id).unread,false);
  const completed=await call(`/api/tickets/${task.id}`,f.manager,'PUT',{status:'completed'});assert.equal(completed.status,200);assert.ok(completed.body.item.resolvedAt);
  overview=(await call('/api/dashboard/overview')).body;assert.ok(!overview.notifications.some(n=>n.entityId===task.id));
  assert.equal((await call(`/api/tickets/${task.id}`,f.manager,'PUT',{status:'new'})).status,400);
  assert.equal((await call(`/api/tickets/${task.id}`,f.manager,'PUT',{status:'new',reopenReason:'Повторная проверка'})).status,200);
  assert.equal((await call('/api/operations/equipment',f.manager,'POST',{name:'Чужое',propertyId:f.other.id,unitId:f.otherUnit.id,type:'Щит'})).status,403);
  assert.equal((await call(`/api/users/${f.worker.id}`,f.manager,'PUT',{isActive:false})).status,200);
  assert.equal((await call('/api/dashboard/overview',f.worker)).status,401);
  assert.equal((await call(`/api/users/${f.admin.id}`,f.manager,'PUT',{role:'worker'})).status,403);
  assert.equal((await call('/api/operations',f.admin)).body.audit.some(e=>e.entityId===f.worker.id),true);
});
