export const industrialCopy = {
  ru: {
    overviewTag: "Промышленный контур",
    finance: "Финансы",
    notifications: "Уведомления",
    team: "Команда",
    tenantRegistry: "Арендаторы",
    tenantPassport: "Паспорт арендатора",
    payments: "Платежи",
    meters: "Счётчики",
    notes: "Переговоры",
    risks: "Риски",
    exports: "Импорт / экспорт",
    cashflow: "Прогноз денежного потока",
    collectionRate: "Сбор платежей",
    arrears: "Просрочка",
    noi: "NOI",
    opex: "Доля операционных расходов",
    forecast: "Прогноз 3 мес.",
    monthlyRent: "Мес. поток",
    paymentDiscipline: "Платёжная дисциплина",
    nextExpiry: "Договор до",
    assigned: "Назначено",
    urgent: "Критично",
    shift: "Смена",
    focus: "Фокус",
    cadence: "Частота",
    scope: "Контур",
    exportStatus: {
      ready: "Готов",
      scheduled: "По расписанию",
      draft: "Черновик",
    },
    paymentStatus: {
      paid: "Оплачен",
      partial: "Частично",
      late: "С задержкой",
      overdue: "Просрочен",
      upcoming: "Ожидается",
    },
    riskSeverity: {
      critical: "Критично",
      warning: "Контроль",
      info: "Норма",
    },
    emptyTenant: "Выберите арендатора из реестра.",
    noNotifications: "Нет активных уведомлений.",
    noTeam: "Команда не найдена.",
    noExports: "Нет доступных выгрузок.",
  },
  en: {
    overviewTag: "Industrial contour",
    finance: "Finance",
    notifications: "Notifications",
    team: "Team",
    tenantRegistry: "Tenants",
    tenantPassport: "Tenant passport",
    payments: "Payments",
    meters: "Meters",
    notes: "Negotiations",
    risks: "Risks",
    exports: "Import / export",
    cashflow: "Cash flow forecast",
    collectionRate: "Collection rate",
    arrears: "Arrears",
    noi: "NOI",
    opex: "OPEX vs budget",
    forecast: "3M forecast",
    monthlyRent: "Monthly flow",
    paymentDiscipline: "Payment discipline",
    nextExpiry: "Lease until",
    assigned: "Assigned",
    urgent: "Critical",
    shift: "Shift",
    focus: "Focus",
    cadence: "Cadence",
    scope: "Scope",
    exportStatus: {
      ready: "Ready",
      scheduled: "Scheduled",
      draft: "Draft",
    },
    paymentStatus: {
      paid: "Paid",
      partial: "Partial",
      late: "Late",
      overdue: "Overdue",
      upcoming: "Upcoming",
    },
    riskSeverity: {
      critical: "Critical",
      warning: "Watch",
      info: "Stable",
    },
    emptyTenant: "Select a tenant from the registry.",
    noNotifications: "No active notifications.",
    noTeam: "No team members found.",
    noExports: "No exports available.",
  },
} as const;

export const managerCopy = {
  ru: {
    shellRole: "Менеджерский контур",
    nav: {
      agenda: "Сроки и работы",
      operations: "Эксплуатация",
      dashboard: "Дашборд",
      tenants: "Арендаторы",
      units: "Помещения",
      leases: "Договоры",
      billing: "Биллинг",
      payments: "Платежи",
      tickets: "Заявки",
      chat: "Чат",
      notifications: "Уведомления",
      objects: "Объекты",
      objectLaunch: "Запуск объекта",
      staff: "Пользователи",
      import: "Импорт / экспорт",
      profile: "Профиль",
    },
    titles: {
      dashboard: "Дашборд",
      tenants: "Арендаторы",
      tenantDetail: "Карточка арендатора",
      tenantAdd: "Новый арендатор",
      objects: "Мой объект",
      propertyAdd: "Новый объект",
      objectLaunch: "Запуск объекта",
      units: "Помещения",
      unitDetail: "Карточка помещения",
      unitAdd: "Новое помещение",
      leases: "Договоры",
      leaseAdd: "Новый договор",
      billing: "Биллинг",
      tickets: "Заявки",
      ticketDetail: "Карточка заявки",
      ticketCreate: "Новая заявка",
      chat: "Чат с арендаторами",
      notifications: "Уведомления",
      staff: "Пользователи",
      staffAdd: "Новый сотрудник",
      import: "Импорт / экспорт",
      profile: "Профиль",
    },
    subtitles: {
      dashboard: "Операционная сводка по объекту, платежам и сервису.",
      tenants: "Реестр арендаторов с переходом в детальную карточку.",
      tenantDetail: "Договоры, платежи, заметки, риски и заявки в одном месте.",
      tenantAdd: "Добавление арендатора с контактами и реквизитами.",
      objects: "Карта объекта, фонд и оперативное перевыделение по площадям.",
      propertyAdd: "Создание нового объекта в том же контуре работы менеджера.",
      objectLaunch:
        "Пошаговый запуск: объект, помещение, арендатор и первый договор.",
      units: "Реестр помещений и их текущее состояние.",
      unitDetail: "Параметры помещения, аренда и сервисная нагрузка.",
      unitAdd: "Создание помещения без ухода в технический раздел.",
      leases: "Сроки, ставки и точки пролонгации по договорам.",
      leaseAdd: "Новый договор с выбором арендатора и помещения.",
      billing: "Счета, частичные оплаты, просрочка и платежные документы.",
      tickets: "Очередь сервисных заявок по объекту.",
      ticketDetail: "Статус, история и комментарии по заявке.",
      ticketCreate: "Создание новой заявки из подтвержденного потока.",
      chat: "Коммуникация с арендаторами на основе связанных заявок.",
      notifications: "События по SLA, договорам и эксплуатации.",
      staff: "Сотрудники и роли по объекту.",
      staffAdd: "Добавление сотрудника с привязкой к объекту.",
      import: "Шаблоны загрузки и готовые выгрузки.",
      profile: "Текущая учетная запись и границы доступа.",
    },
    back: "Назад",
    add: "Добавить",
    import: "Импорт",
    open: "Открыть",
    emptyChat:
      "Для этого арендатора пока нет сообщений. Новое сообщение уйдет в комментарии по его последней заявке.",
    noThreadTarget: "Нет связанной заявки, куда можно отправить сообщение.",
    chatPlaceholder: "Сообщение арендатору",
    chatThreadMeta: "связанные заявки",
    unitMeta: "Текущее состояние",
    templates: "Шаблоны импорта",
    readyExports: "Готовые выгрузки",
    profileScope: "Контур доступа",
    linkedTickets: "Связанные заявки",
    leaseHistory: "История договоров",
    baseInfo: "Основная информация",
    access: "Доступ в систему",
    operations: "Операции",
    createStaff: "Создать сотрудника",
    send: "Отправить",
    phoneOptional: "Телефон",
    passwordTemp: "Временный пароль",
    objectScope: "Привязка к объекту",
    allObjects: "Без привязки",
    security: "Безопасность",
    totpEnabled: "2FA включена",
    totpDisabled: "2FA выключена",
    totpSetup: "Подключить 2FA",
    totpDisable: "Отключить 2FA",
    totpSecret: "Ключ TOTP",
    totpConfirmHint: "Добавьте ключ в Authenticator и введите 6-значный код.",
    totpDisableHint: "Введите пароль и текущий код 2FA.",
    confirm: "Подтвердить",
  },
  en: {
    shellRole: "Manager contour",
    nav: {
      agenda: "Сроки и работы",
      operations: "Эксплуатация",
      dashboard: "Dashboard",
      tenants: "Tenants",
      units: "Units",
      leases: "Leases",
      billing: "Billing",
      payments: "Payments",
      tickets: "Tickets",
      chat: "Chat",
      notifications: "Notifications",
      objects: "Objects",
      objectLaunch: "Object launch",
      staff: "Users",
      import: "Import / export",
      profile: "Profile",
    },
    titles: {
      dashboard: "Dashboard",
      tenants: "Tenants",
      tenantDetail: "Tenant detail",
      tenantAdd: "New tenant",
      objects: "My property",
      propertyAdd: "New property",
      objectLaunch: "Object launch",
      units: "Units",
      unitDetail: "Unit detail",
      unitAdd: "New unit",
      leases: "Leases",
      leaseAdd: "New lease",
      billing: "Billing",
      tickets: "Tickets",
      ticketDetail: "Ticket detail",
      ticketCreate: "New ticket",
      chat: "Tenant chat",
      notifications: "Notifications",
      staff: "Users",
      staffAdd: "New staff member",
      import: "Import / export",
      profile: "Profile",
    },
    subtitles: {
      dashboard:
        "Operational summary for the property, payments, and service load.",
      tenants: "Tenant registry with direct access to the detail card.",
      tenantDetail: "Leases, payments, notes, risks, and tickets in one place.",
      tenantAdd: "Add a tenant without switching to a technical admin panel.",
      objects: "Property map, stock, and fast context switching by property.",
      propertyAdd: "Create a new property inside the same manager flow.",
      objectLaunch:
        "Step-by-step launch: property, unit, tenant, and first lease.",
      units: "Unit registry and current condition.",
      unitDetail: "Unit parameters, lease state, and service load.",
      unitAdd: "Create a unit without leaving the operating contour.",
      leases: "Terms, rates, and renewal points across leases.",
      leaseAdd: "New lease with tenant and unit selection.",
      billing: "Invoices, partial payments, arrears, and payment ledger.",
      tickets: "Service queue for the assigned portfolio.",
      ticketDetail: "Status, history, and comments for the ticket.",
      ticketCreate: "Create a new ticket in the confirmed flow.",
      chat: "Tenant communication backed by related tickets.",
      notifications: "Events across SLA, leases, and operations.",
      staff: "Staff and roles for the property.",
      staffAdd: "Add a staff member and attach them to a property.",
      import: "Upload templates and export queue.",
      profile: "Current account and access boundaries.",
    },
    back: "Back",
    add: "Add",
    import: "Import",
    open: "Open",
    emptyChat:
      "No messages for this tenant yet. A new message will be posted into comments for the latest related ticket.",
    noThreadTarget: "There is no related ticket to send the message to.",
    chatPlaceholder: "Message to tenant",
    chatThreadMeta: "linked tickets",
    unitMeta: "Current condition",
    templates: "Import templates",
    readyExports: "Ready exports",
    profileScope: "Access scope",
    linkedTickets: "Linked tickets",
    leaseHistory: "Lease history",
    baseInfo: "Base information",
    access: "System access",
    operations: "Operations",
    createStaff: "Create staff member",
    send: "Send",
    phoneOptional: "Phone",
    passwordTemp: "Temporary password",
    objectScope: "Property scope",
    allObjects: "No property binding",
    security: "Security",
    totpEnabled: "2FA enabled",
    totpDisabled: "2FA disabled",
    totpSetup: "Enable 2FA",
    totpDisable: "Disable 2FA",
    totpSecret: "TOTP key",
    totpConfirmHint:
      "Add the key to an Authenticator app and enter the 6-digit code.",
    totpDisableHint: "Enter your password and current 2FA code.",
    confirm: "Confirm",
  },
} as const;
